version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    networks:
      - external_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hibiki
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  hibiki:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hibiki
    networks:
      - external_net
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: always

networks:
  external_net:
    driver: bridge

volumes:
  postgres-data:
